[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10}
opacity = 0.8
# decorations = "None"
blur = true

[font]
size = 12

[font.bold]
family = "0xProto Nerd Font"
style = "Bold"

[font.bold_italic]
family = "0xProto Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "0xProto Nerd Font"
style = "Italic"

[font.normal]
family = "0xProto Nerd Font"
style = "Regular"

[colors.primary]
background = "#181818"
foreground = "#d8d8d8"
dim_foreground = "#181818"
