[window]
opacity = 0.9

[window.padding]
x = 10
y = 10

[font]
size = 11.9

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regualar"

[font.offset]
x = 0
y = 1
