[window]
opacity = 0.9

[window.padding]
x = 10
y = 10

[font]
size = 12

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1

[colors.primary]
background = "#181818"
foreground = "#d8d8d8"
dim_foreground = "#181818"
